import { Language } from './i18n';

export interface PrivacySection {
  title: string;
  body: string;
}

export interface PrivacyPolicy {
  title: string;
  lastUpdated: string;
  intro: string;
  sections: PrivacySection[];
  contact: string;
}

const APP_NAME = 'QR & Barcode Scanner';
const CONTACT_EMAIL = 'valdezgzz.22@gmail.com';
const LAST_UPDATED = '17 de abril de 2025';
const LAST_UPDATED_EN = 'April 17, 2025';

const es: PrivacyPolicy = {
  title: 'Política de Privacidad',
  lastUpdated: `Última actualización: ${LAST_UPDATED}`,
  intro: `Esta Política de Privacidad describe cómo ${APP_NAME} ("la app", "nosotros") maneja la información cuando usas nuestra aplicación móvil. Al usar la app, aceptas las prácticas descritas en este documento.`,
  sections: [
    {
      title: '1. Información que recopilamos',
      body: `La app no recopila ni transmite información personal identificable a nuestros servidores.\n\nToda la información generada por el uso de la app (historial de escaneos, configuración, favoritos) se almacena exclusivamente en el almacenamiento local de tu dispositivo y nunca sale de él.\n\nLos únicos datos procesados son:\n• Contenido de los códigos QR y de barras que escaneas (procesado únicamente en el dispositivo).\n• Imágenes de la galería que seleccionas voluntariamente para escanear (procesadas en el dispositivo, no almacenadas ni transmitidas).\n• Configuración de preferencias de la app (tema, idioma, color de acento, activación de hápticos).`,
    },
    {
      title: '2. Permisos que solicitamos',
      body: `La app solicita los siguientes permisos del sistema:\n\n• Cámara: necesario para escanear códigos QR y de barras en tiempo real. No se graban ni almacenan imágenes de la cámara.\n• Galería / Fotos: necesario para seleccionar imágenes desde las que deseas escanear un código. Las imágenes no se copian ni se transmiten.\n• Contactos: necesario únicamente al guardar un contacto desde un código vCard. La app solo escribe el contacto que tú solicitas; no lee ni exporta tu lista de contactos.\n\nNingún permiso se utiliza para rastrear tu ubicación, acceder a archivos no relacionados con la función descrita o recopilar datos de uso.`,
    },
    {
      title: '3. Publicidad (Google AdMob)',
      body: `La versión gratuita de la app muestra anuncios proporcionados por Google AdMob. Google puede recopilar ciertos datos para personalizar los anuncios según su propia Política de Privacidad.\n\nPuedes consultar cómo Google gestiona tu información en: https://policies.google.com/privacy\n\nLa versión Pro elimina todos los anuncios de forma permanente, sin suscripción ni renovaciones automáticas.`,
    },
    {
      title: '4. Almacenamiento local',
      body: `El historial de escaneos (máximo 20 entradas), los favoritos y la configuración de la app se guardan en el almacenamiento local del dispositivo mediante AsyncStorage. Estos datos permanecen en tu dispositivo y se eliminan al desinstalar la app.`,
    },
    {
      title: '5. Servicios de terceros',
      body: `La app puede utilizar los siguientes servicios de terceros:\n\n• Google AdMob (publicidad en versión gratuita): https://policies.google.com/privacy\n• Expo / React Native (plataforma de desarrollo): https://expo.dev/privacy\n• RevenueCat (gestión de compras in-app, versión Pro): https://www.revenuecat.com/privacy\n\nEstos servicios tienen sus propias políticas de privacidad que te recomendamos revisar.`,
    },
    {
      title: '6. Menores de edad',
      body: `Esta app no está dirigida a menores de 13 años. No recopilamos conscientemente información de menores. Si eres padre o tutor y crees que tu hijo ha proporcionado información personal, contáctanos para que podamos tomar las medidas necesarias.`,
    },
    {
      title: '7. Cambios a esta política',
      body: `Podemos actualizar esta Política de Privacidad ocasionalmente. Te notificaremos de cualquier cambio publicando la nueva versión en esta página con la fecha de última actualización. Te recomendamos revisar esta política periódicamente.`,
    },
    {
      title: '8. Contacto',
      body: `Si tienes preguntas sobre esta Política de Privacidad, puedes contactarnos en:\n\n${CONTACT_EMAIL}`,
    },
  ],
  contact: CONTACT_EMAIL,
};

const en: PrivacyPolicy = {
  title: 'Privacy Policy',
  lastUpdated: `Last updated: ${LAST_UPDATED_EN}`,
  intro: `This Privacy Policy describes how ${APP_NAME} ("the app", "we") handles information when you use our mobile application. By using the app, you agree to the practices described in this document.`,
  sections: [
    {
      title: '1. Information We Collect',
      body: `The app does not collect or transmit personally identifiable information to our servers.\n\nAll information generated by using the app (scan history, settings, favorites) is stored exclusively on your device's local storage and never leaves it.\n\nThe only data processed is:\n• Content of QR codes and barcodes you scan (processed on-device only).\n• Gallery images you voluntarily select for scanning (processed on-device, not stored or transmitted).\n• App preference settings (theme, language, accent color, haptics toggle).`,
    },
    {
      title: '2. Permissions We Request',
      body: `The app requests the following system permissions:\n\n• Camera: required to scan QR codes and barcodes in real time. No camera images are recorded or stored.\n• Gallery / Photos: required to select images from which you want to scan a code. Images are not copied or transmitted.\n• Contacts: required only when saving a contact from a vCard code. The app only writes the contact you request; it does not read or export your contact list.\n\nNo permission is used to track your location, access files unrelated to the described function, or collect usage data.`,
    },
    {
      title: '3. Advertising (Google AdMob)',
      body: `The free version of the app displays ads provided by Google AdMob. Google may collect certain data to personalize ads according to their own Privacy Policy.\n\nYou can learn how Google manages your information at: https://policies.google.com/privacy\n\nThe Pro version permanently removes all ads — no subscription, no automatic renewals.`,
    },
    {
      title: '4. Local Storage',
      body: `Scan history (up to 20 entries), favorites, and app settings are saved to the device's local storage via AsyncStorage. This data stays on your device and is deleted when you uninstall the app.`,
    },
    {
      title: '5. Third-Party Services',
      body: `The app may use the following third-party services:\n\n• Google AdMob (advertising in free version): https://policies.google.com/privacy\n• Expo / React Native (development platform): https://expo.dev/privacy\n• RevenueCat (in-app purchase management, Pro version): https://www.revenuecat.com/privacy\n\nThese services have their own privacy policies, which we encourage you to review.`,
    },
    {
      title: '6. Children',
      body: `This app is not directed to children under 13. We do not knowingly collect information from children. If you are a parent or guardian and believe your child has provided personal information, please contact us so we can take appropriate action.`,
    },
    {
      title: '7. Changes to This Policy',
      body: `We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new version on this page with the updated date. We recommend reviewing this policy periodically.`,
    },
    {
      title: '8. Contact',
      body: `If you have questions about this Privacy Policy, you can contact us at:\n\n${CONTACT_EMAIL}`,
    },
  ],
  contact: CONTACT_EMAIL,
};

export const privacyContent: Record<Language, PrivacyPolicy> = { es, en };
